enum City {
  AVEIRO = "Aveiro",
  PORTO = "Porto",
  LISBOA = "Lisboa",
  BRAGA = "Braga",
  VISEU = "Viseu",
  ESPINHO = "Espinho",
  COIMBRA = "Coimbra",
  FARO = "Faro",
  PORTIMAO = "Portimão",
  FUNCHAL = "Funchal",
  PONTA_DELGADA = "Ponta Delgada",
  LEIRIA = "Leiria",
  GUARDA = "Guarda",
  BRAGANCA = "Bragança",
  VILA_NOVA_DE_GAIA = "Vila Nova de Gaia",
  GUIMARAES = "Guimarães",
  SINTRA = "Sintra",
  BEJA = "Beja",
  EVORA = "Évora",
}
