export default [
  'Expansion for Base-game',
  'Korean War',
  'Napoleonic',
  'Renaissance',
  'Print & Play',
  'Video Game Theme',
  'World War I',
  'World War II',
  'Fan Expansion',
  'Civil War',
  'Post-Napoleonic',
  'Vietnam War',
  'Pike and Shot',
  'Space Exploration',
  'Collectible Components',
  'American Revolutionary War',
  'American Civil War',
  'American Indian Wars',
  'Number',
  'Electronic',
  'Arabian',
];
