export default [
  'Auction: Dutch',
  'Auction: Dutch Priority',
  'Crayon Rail System',
  'I Cut, You Choose',
  'Worker Placement, Different Worker Types',
  'Deck, Bag, and Pool Building',
  'Mancala',
  'Rondel',
  'Take That',
  'Hot Potato',
  'Force Commitment',
  'Bias',
  'Auction: Dexterity',
  'Auction: English',
  'Auction: Once Around',
  'Auction: Turn Order Until Pass',
  'Auction: Sealed Bid',
  'Auction: Fixed Placement',
  'Bingo',
  'Chaining',
  'Chit-Pull System',
  'Commodity Speculation',
  'Worker Placement with Dice Workers',
  '"Worker Placement, Different Worker Types"',
  '"Deck, Bag, and Pool Building"',
  'Multiple-Lot Auction',
  'Pieces as Map',
  'Selection Order Bid',
  'Stock Holding',
  'Victory Points as a Resource',
  'Interrupts',
];
